version: '3.7'
services:
  chat-app-mongodb:
    image: mongo
    ports:
      - '27017:27017'
    container_name: chat-app-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - chat-app-volume-mongo:/data/db
    networks:
      - chat-app-network
    restart: always

  chat-app-postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    container_name: chat-app-postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat-app-user
      APP_DB_USER: docker
      APP_DB_PASS: docker
      APP_DB_NAME: chat-app-user
    volumes:
      - chat-app-volume-postgres:/var/lib/postgresql/data
    networks:
      - chat-app-network
    restart: always

  chat-app-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: chat-app-elasticsearch
    environment:
      - cluster.name=chat-app-cluster
      - node.name=node1
      - discovery.type=single-node
      # - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - chat-app-volume-esdata:/usr/share/elasticsearch/data
    restart: always
    networks:
      - chat-app-network

  chat-app-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: chat-app-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - chat-app-network
    restart: unless-stopped

  chat-app-user1:
    build:
      dockerfile: Dockerfile
      context: ./user
    container_name: chat-app-user1
    environment:
      - PORT=5001
    volumes:
      - .:/app
      - /app/user/node_modules
    depends_on:
      - chat-app-postgres
      - chat-app-elasticsearch
      - chat-app-rabbitmq
    networks:
      - chat-app-network
    restart: always
    env_file:
      - ./user/.env.example

  chat-app-user2:
    build:
      dockerfile: Dockerfile
      context: ./user
    container_name: chat-app-user2
    environment:
      - PORT=5002
    volumes:
      - .:/app
      - /app/user/node_modules
    depends_on:
      - chat-app-postgres
      - chat-app-elasticsearch
      - chat-app-rabbitmq
    networks:
      - chat-app-network
    restart: always
    env_file:
      - ./user/.env.example

  chat-app-user3:
    build:
      dockerfile: Dockerfile
      context: ./user
    container_name: chat-app-user3
    environment:
      - PORT=5003
    volumes:
      - .:/app
      - /app/user/node_modules
    depends_on:
      - chat-app-postgres
      - chat-app-elasticsearch
      - chat-app-rabbitmq
    networks:
      - chat-app-network
    restart: always
    env_file:
      - ./user/.env.example

  chat-app-chat1:
    build:
      dockerfile: Dockerfile
      context: ./chat
    container_name: chat-app-chat1
    environment:
      - PORT=5101
    volumes:
      - .:/app
      - /app/chat/node_modules
    depends_on:
      - chat-app-mongodb
      - chat-app-elasticsearch
      - chat-app-rabbitmq
    networks:
      - chat-app-network
    restart: always
    env_file:
      - ./chat/.env.example

  chat-app-chat2:
    build:
      dockerfile: Dockerfile
      context: ./chat
    container_name: chat-app-chat2
    environment:
      - PORT=5102
    volumes:
      - .:/app
      - /app/chat/node_modules
    depends_on:
      - chat-app-mongodb
      - chat-app-elasticsearch
      - chat-app-rabbitmq
    networks:
      - chat-app-network
    restart: always
    env_file:
      - ./chat/.env.example

  chat-app-chat3:
    build:
      dockerfile: Dockerfile
      context: ./chat
    container_name: chat-app-chat3
    environment:
      - PORT=5103
    volumes:
      - .:/app
      - /app/chat/node_modules
    depends_on:
      - chat-app-mongodb
      - chat-app-elasticsearch
      - chat-app-rabbitmq
    networks:
      - chat-app-network
    restart: always
    env_file:
      - ./chat/.env.example

  chat-app-message1:
    build:
      dockerfile: Dockerfile
      context: ./message
    container_name: chat-app-message1
    environment:
      - PORT=5201
    volumes:
      - .:/app
      - /app/message/node_modules
    depends_on:
      - chat-app-mongodb
      - chat-app-elasticsearch
      - chat-app-rabbitmq
    networks:
      - chat-app-network
    restart: always
    env_file:
      - ./message/.env.example

  chat-app-message2:
    build:
      dockerfile: Dockerfile
      context: ./message
    container_name: chat-app-message2
    environment:
      - PORT=5202
    volumes:
      - .:/app
      - /app/message/node_modules
    depends_on:
      - chat-app-mongodb
      - chat-app-elasticsearch
      - chat-app-rabbitmq
    networks:
      - chat-app-network
    restart: always
    env_file:
      - ./message/.env.example

  chat-app-message3:
    build:
      dockerfile: Dockerfile
      context: ./message
    container_name: chat-app-message3
    environment:
      - PORT=5203
    volumes:
      - .:/app
      - /app/message/node_modules
    depends_on:
      - chat-app-mongodb
      - chat-app-elasticsearch
      - chat-app-rabbitmq
    networks:
      - chat-app-network
    restart: always
    env_file:
      - ./message/.env.example

  chat-app-frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: chat-app-frontend
    ports:
      - '3000:5173'
    volumes:
      - .:/app
      - /app/frontend/node_modules
    depends_on:
      - chat-app-postgres
      - chat-app-mongodb
      - chat-app-elasticsearch
      - chat-app-rabbitmq
    networks:
      - chat-app-network
    restart: always

  chat-app-nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on:
      - chat-app-user1
      - chat-app-user2
      - chat-app-user3
      - chat-app-chat1
      - chat-app-chat2
      - chat-app-chat3
      - chat-app-message1
      - chat-app-message2
      - chat-app-message3
      - chat-app-frontend
    networks:
      - chat-app-network
    restart: always
    ports:
      - 80:80

volumes:
  chat-app-volume-postgres:
  chat-app-volume-mongo:
  chat-app-volume-esdata:

networks:
  chat-app-network:
